#server:
#  port: 8080
spring:
  application:
    name: API-Gateway
#  cloud:
#    gateway:
#      routes:
#            - id: user-service
#              uri: lb://USER-SERVICE
#              predicates:
#                - Path=/api/v1/user/**
#            - id: activity-service
#              uri: lb://ACTIVITY-SERVICE
#              predicates:
#                - Path=/api/v1/activities/**
#            - id: ai-service
#              uri: lb://AI-SERVICE
#              predicates:
#                - Path=/api/v1/recommendations/**
#eureka:
#  client:
#        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
  config:
    import: optional:configserver:http://localhost:8888
